package Source;

public enum ServerResponseType {
    OK,
    INVALID,

    DISCONNECTED,
    OTHER_PLAYER_CONNECTED,

    DEPLOYED_DESTROYER,
    DEPLOYED_CRUISER,
    DEPLOYED_BATTLESHIP,
    DEPLOYED_CARRIER,

    NOTHING_OF_IMPORTANCE
}
