public enum MessageType {
    LOGIN,
    LOGOUT,
    GAME_COMMAND,
    JOIN_GAME,
    JOIN_RANDOM_GAME,
    EXIT_GAME,
    SAVE_GAME,
    LOAD_GAME,
    DELETE_GAME,
    SEARCH_GAMES,
    CREATE_GAME,
    SHOW_PLAYER_STATISTICS,
    CUSTOM_MESSAGE
}
